### ISSUE TITLE
Bonemeal doesn't work on saplings

### ISSUE THREAD

**Issue by crabdancing** [Phlenum/Combustible-Lemon-Launcher#3]
If this is an intended behavior, please make it configurable! Thanks. :)

**Comment by Phlenum** [comment]
What version of the mod are you using? It might be that I just implemented this behaviour later on. On the current version it works just fine. (Or maybe there's another mod that overrides bone meal's behaviour entirely?

**Comment by alxpettit** [comment]
I was using `CLL-1.12.2-3.5.14.jar` -- but that was with an old modpack and the entire world + modpack has been changed sadly. But I can confirm that I had that problem as of that version. Sadly, I can no longer debug the problem without redoing my entire setup.

**Comment by Phlenum** [comment]
I'm using the vanilla functionality so it _should_ be fine on my end. I'm guessing there was a mod that altered the behaviour of bone meal or plants and their growth. I'll close this for now but if the error occurs again I'll look into it!
